### ISSUE TITLE
Review of three repos, starting with first-null-commit,  and proposed org roles.

### ISSUE THREAD

**Issue by jdonson** [jdonson/first-null-commit#2]
Git and GitHub Team Dev => See It, Do It, Teach It!

TEAM DEV INITIATION TASKS

Task 1:     Register With Dev Team + Get Kitchen Set Up (OS, Browser, Skype, irc, github, cacoo, codepen)

Task 2:     Clone to local and Null Commit to First-Null-Commit repo.  Straight solo push.

Task 3:     First problem:  github origin repo is ahead of your local repo

Task 4:     Second problem:  same, but you wanted to undo your last prior commit

Task 5:     Third problem:  same, but you also just committed to local repo and have not yet pushed.  Deadlock?

Task 6:     Use diagrams to clarify the conflicts at play.

Task 7:     Leverage GitHub Issues to organize tasks!

Task 8:     Make this repo part of another repo:  github-project-team-dev-onboarding

Task 9:     Consider branches and merges to keep commits current and master pure.

**Comment by jdonson** [comment]
Three Repos For Nitesh:
1.  First Null Commit
2.  Git Team Dev Dojo
3.  OSS Barter Tools

The comment above is a framing of how to get started in the second repo:  git-team-dev-dojo

By identifying all team dev github repo issues with local and remote dev on-boarding and addressing them here, we can learn to detect, resolve and prevent code conflicts by design in team dev workflows.

**Comment by jdonson** [comment]
Lots of repo content needs to be moved to wiki pages.

**Comment by jdonson** [comment]
We will use cacoo to diagram git conflicts.

CodePen and other sites are worth learning about.

Github uses this service for their training....

https://www.codeschool.com/account/courses/try-git/add

**Comment by Niteshvgupta** [comment]
Just did the first course on codeschool, it was really helpful.
