### ISSUE TITLE
Please learn about codepen.io

### ISSUE THREAD

**Issue by jdonson** [jdonson/first-null-commit#5]
Note that I labeled this issue a QUESTION!  Labels are to the right =>

Here are the sites where we can leverage free OSS edu services:

==> Description  :    Name    :   URL

Source Code Mgt & Distrib : Github : github .com

Photoediting : Pixlr : pixlr.com

Diagrams : Cacoo :  cacoo.com

Conferencing : Skype : Skype.com

Forums : Facebook Groups : https://www.facebook.com/groups/osswebdevbackend/

Flashcards : Course Hero : http://www.coursehero.com

GitHub Pro Training CodeSchool Service:  https://www.codeschool.com/account/courses/try-git/add

Code Teaching : CodePen : codepen.io

Please learn about codepen slowly and set up a time to teach it to me!

**Comment by Niteshvgupta** [comment]
Created a codepen account, slowly learning.

Also, when do you think the right time to start the "GitHub Pro Training CodeSchool Service"?

**Comment by jdonson** [comment]
We would need to get thru several chapters of that git book
and also have the Git-Team-Dev-Dojo repo set up.

Once you are trying to onboard local and remote folks, you will see
why we need to do this in chewable bites.

We can start now by creating an internship description for front end web site
designer who can make a responsive theme for your web site.

http://en.wikipedia.org/wiki/Responsive_Web_Design

You will want to share code thru a private hosted github repo with this Themer.

If they say they are git savvy, then ask for their github id
and add them to first-null-commit repo and see if they can do a commit.  ;)
